### ISSUE TITLE
How to use abilities

### ISSUE THREAD

**Issue by vampiregoat699** [0vergrown/Voidwalker-Origin#1]
Not sure how to use any ability I don't know what keys to use to do anything

**Comment by 0vergrown** [comment]
Your reading comprehension is so atrociously bad that you need to go back to school. It’s not only shown in the badges that tell the exact key you can use, but it’s also shown in the ability description which keys you have to press in order to use them. If they are not bound, you can go into the controls and bind them. It’s not really a hard concept; it’s a skill issue.
